credit_card_dwh:
  outputs:
    dev:
      dataset: raw_credit_card
      fixed_retries: 1
      keyfile: /service-account.json
      location: us-central1
      method: service-account
      priority: interactive
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      threads: 4
      timeout_seconds: 300
      type: bigquery
    prod:
      dataset: credit_card_dwh_prod
      fixed_retries: 1
      keyfile: /service-account.json
      location: us-central1
      method: service-account
      priority: interactive
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      threads: 4
      timeout_seconds: 300
      type: bigquery
  target: dev